# Generated by Django 4.2.1 on 2023-06-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='biog',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='performer',
            name='weblink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
