# Generated by Django 4.2.1 on 2023-06-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_performer_biog_alter_performer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='performers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.performer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
