# Generated by Django 4.2.1 on 2023-06-27 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0005_alter_event_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'start_time', 'venue__name']},
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
    ]
